name: Build and Release

on:
  push:
    tags: [ "v*" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'
      
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      
      - name: Set up Signing Key
        run: |
          # 只有在 Github Secrets 中配置了 KEYSTORE_BASE64 才配置
          if [ ! -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            # 请将 keystore 以 base64 的形式储存在 Github Secrets 中
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore
            echo "storeFile=../keystore" > signing.properties
            echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> signing.properties
            echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> signing.properties
            echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> signing.properties
          fi
          
      - name: Build with Gradle
        id: build
        run: |
          chmod +x ./gradlew
          start_time="$(date +%s)"
          ./gradlew assembleRelease
          end_time="$(date +%s)"

          duration_seconds=$((end_time - start_time))
          duration_minutes=$((duration_seconds / 60))
          duration_remainder=$((duration_seconds % 60))
          printf -v duration_human "%dm %02ds" "$duration_minutes" "$duration_remainder"
          
          echo "APK=$(find ./app/build/outputs/apk/release -name "*.apk")" >> $GITHUB_OUTPUT
          echo "build_duration=$duration_human" >> $GITHUB_OUTPUT
      
      - name: Generate Release Notes
        run: |
          extract() {
            basename "${{ steps.build.outputs.APK }}" | cut -d'-' -f"$1"
          }
          Version=$(extract 2 | sed 's/^v//')
          VersionCode=$(extract 3)
          {
            echo "- **Version:** \`${VERSION_NAME}\`"
            echo "- **VersionCode:** \`${VERSION_CODE}\`"
            echo "- **Build time:** \`${{ steps.build.outputs.build_duration }}\`"
            echo
            echo "## What's Changed"
            echo
            echo "待补充"
          } > release-note.md
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          name: "${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: false
          files: ${{ steps.build.outputs.APK }}
          body: release-note.md
          